WEBAPP_URL = 'https://link.ngrok-free.app'
BOT_TOKEN = ''
WEBHOOK_HOST = 'https://link.ngrok-free.app'
WEBHOOK_PATH = 'webhook'
ENGINE = f'postgresql+asyncpg://vehicle:vehicle@vehicle-postgres:5432/vehicle'
ADMIN_USERNAME = 'admin'
ADMIN_PASSWORD = 'qwerty'
